waypoints:
# Random points:
  - [0.0, 0.0]
  - [6.0, 0.0]
  - [6.0, 6.0]
  - [0.0, 6.0]
  - [0.0, 0.0]

# #square: 
#   - [0.0, 0.0]
#   - [2.0, 0.0]
#   - [2.0, 2.0]
#   - [0.0, 2.0]
#   - [0.0, 0.0]

# #line: 
#   - [0.0, 0.0]
#   - [2.0, 2.0]
#   - [4.0, 4.0]
#   - [6.0, 6.0]
#   - [8.0, 8.0]

# #zigzag:
#   - [0.0, 0.0]
#   - [2.0, 2.0]
#   - [4.0, 0.0]
#   - [6.0, 2.0]
#   - [8.0, 0.0]